repos:
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.46.0  # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false
        language: system  # Use system-installed pyrefly